services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/java
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - s-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: java
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5433"
    networks:
      - s-network

networks:
  s-network:
    driver: bridge




